version: 2.1

jobs:
  # This job creates a file
  create-data:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - run:
          name: "Create an output file"
          command: |
            mkdir -p my_output
            echo "Data from the first job" > my_output/output.txt
      # Persist the my_output directory to the workspace for the next job
      - persist_to_workspace:
          root: . # Relative to the project root
          paths:
            - my_output

  # This job reads the file created by the previous job
  process-data:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      # Attach the workspace saved in the previous job
      - attach_workspace:
          at: . # Attach at the project root
      - run:
          name: "Process the output file"
          command: |
            echo "Reading file from previous job:"
            cat my_output/output.txt

workflows:
  sequential-workflow:
    jobs:
      - create-data
      - process-data:
          requires: # This makes the workflow sequential
            - create-data