version: 2.1

orbs:
  slack: circleci/slack@4.12.5

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Simulate Work
          command: echo "✅ Build complete"
      - slack/notify:
          event: always
          template: basic_success_1

workflows:
  version: 2
  build_and_notify:
    jobs:
      - build
