version: 2.1

executors:
  my-executor:
    docker:
      - image: buildpack-deps:jessie
    working_directory: /tmp

jobs:
  create_file:
    executor: my-executor

    steps:
      - run: mkdir -p workspace
      - run: echo "Hello, world!" > workspace/echo-output
      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output
    

  read_file:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Read file
          command: cat /tmp/workspace/echo-output
      - run:
          name: List workspace contents
          command: ls -R /tmp/workspace
      - run:
          name: Show file content
          command: cat /tmp/workspace/echo-output

workflows:
  use_workspace:
    jobs:
      - create_file
      - read_file:
          requires:
            - create_file
