version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Build Job
          command: echo "🔨 Build step done"

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Test Job
          command: echo "🧪 Running tests..."

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy Job
          command: echo "🚀 Deploying app..."

workflows:
  version: 2
  demo-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
